Добавлен тест логина
sk8higher/MonkkeeTests pull request #1
Opened 2021-01-17 15:37 UTC by sk8higher

Добавлен Login Test и Login Page.

2021-01-18 16:38 UTC, vshvets requested changes

2021-01-18 16:38 UTC, vshvets commented on src/test/java/pages/LoginPage.java
> +    private final String EMAIL = System.getenv("MONKKEE_EMAIL");
Засунуть в проперти

2021-01-18 16:38 UTC, vshvets commented on src/test/java/pages/LoginPage.java
> +    @FindBy(className = "btn-primary")
желательно использоыать другой локатор

2021-01-18 16:38 UTC, vshvets commented on src/test/java/pages/LoginPage.java
> +        System.out.println(EMAIL);
Использый логгер.  Если будет потом использоваться ставь TODO

2021-01-18 16:38 UTC, vshvets commented on src/test/java/tests/LoginTest.java
> +    public void beforeMethod() {
Пиши вебдрайвер фэктори

2021-01-18 16:38 UTC, vshvets commented on src/test/java/tests/LoginTest.java
> +        wait.until(ExpectedConditions.urlMatches("https://my.monkkee.com/#/entries")); // explicit waiting for page to load
надо в пэйджу в метод засунуть

2021-01-21 16:49 UTC, vshvets requested changes

2021-01-21 16:49 UTC, vshvets commented on src/test/java/pages/LoginPage.java
> +    @FindBy(xpath = "//*[@id='main']/div/div[2]/div[1]/div/div/form/div[4]/div/button/div")
тут поменять на //*[@type = 'submit'] или к тексту

2021-01-21 16:49 UTC, vshvets commented on src/test/java/pages/LoginPage.java
> +        PageFactory.initElements(new AjaxElementLocatorFactory(driver, 2), this);
тут увеличить до 10 секунд и вынести это в проперти

2021-01-21 16:49 UTC, vshvets commented on src/test/java/pages/LoginPage.java
> +        wait = new WebDriverWait(driver, 10, 1000);
создать бэйз тест и туда создание вейтера засунуть или еще куда

2021-01-23 14:21 UTC, sk8higher commented
тесты падают в firefox

2021-01-23 15:02 UTC, sk8higher commented
![image](https://user-images.githubusercontent.com/30351533/105597483-08968000-5da5-11eb-96c9-23a84122658a.png)
в хроме все работает стабильно, с поп апом и без, в фаерфоксе видимо не срабатывают waiter`ы, и когда появляется поп ап оно падает

2021-01-25 16:17 UTC, vshvets approved these changes
ПРо FF два решения:
JS: .scrollIntoView(arguments[0]true);", element
чере экшан: actions.moveToElement(element);

2021-01-25 17:01 UTC, merged