Добавлены новые тесты
sk8higher/MonkkeeTests pull request #5
Opened 2021-02-01 17:34 UTC by sk8higher

Тест на создание записи и тест на удаление всех записей

2021-02-02 14:57 UTC, sk8higher commented
периодически один тест падает в фаерфоксе, нужен фикс

2021-02-02 18:36 UTC, sk8higher commented
не работает

2021-02-04 16:28 UTC, vshvets requested changes

2021-02-04 16:28 UTC, vshvets commented on src/test/java/pages/EntriesPage.java
> +        WebElement textBox = driver.findElement(By.id("editable"));
редактор отдельной страницей

2021-02-04 16:28 UTC, vshvets commented on src/test/java/pages/EntriesPage.java
> +    public EntriesPage returnToHomePage() {
что-то с этим сделать. Или в бэйз пейдз. или навигироваться кнопками на сайте

2021-02-04 16:28 UTC, vshvets commented on src/test/java/pages/EntriesPage.java
> +    public boolean findReturnButton() {
нэйминг . isReturnButtonDisplayed

2021-02-04 16:28 UTC, vshvets commented on src/test/java/tests/DeleteAllEntriesTest.java
> +    @Test(description = "Delete all entries", groups = {"entrypage"}, priority = 1)
Приорити не нужно при изолированных тестах. Лействитеотно ли они независимы? Нужно ли здесь приорити

2021-02-06 14:40 UTC, merged